In [1]:
%load_ext autoreload
%autoreload 2
import sqlalchemy as sa
import pandas as pd
import pudl
import re
pudl_settings = pudl.workspace.setup.get_defaults()
pudl_settings

{'pudl_in': '/Users/stevenwinter/Desktop/pudl-work',
 'data_dir': '/Users/stevenwinter/Desktop/pudl-work/data',
 'settings_dir': '/Users/stevenwinter/Desktop/pudl-work/settings',
 'pudl_out': '/Users/stevenwinter/Desktop/pudl-work',
 'sqlite_dir': '/Users/stevenwinter/Desktop/pudl-work/sqlite',
 'parquet_dir': '/Users/stevenwinter/Desktop/pudl-work/parquet',
 'datapackage_dir': '/Users/stevenwinter/Desktop/pudl-work/datapackage',
 'notebook_dir': '/Users/stevenwinter/Desktop/pudl-work/notebook',
 'ferc1_db': 'sqlite:////Users/stevenwinter/Desktop/pudl-work/sqlite/ferc1.sqlite',
 'pudl_db': 'sqlite:////Users/stevenwinter/Desktop/pudl-work/sqlite/pudl.sqlite'}

In [ ]:
table name you're looking at, what year you're looking at

In [4]:
ferc1_engine = sa.create_engine(pudl_settings['ferc1_db'])

In [5]:
row_literals = pd.read_sql("f1_row_lit_tbl", ferc1_engine)

In [6]:
elec_income_row_literals = (
    row_literals.query("sched_table_name=='f1_incm_stmnt_2'")
)

In [11]:
(
    elec_income_row_literals
    .query("report_year==2017")
    .sort_values("row_number")
)

,sched_table_name,report_year,row_number,row_seq,row_literal,row_status,row_chg_yr
64546,f1_incm_stmnt_2,2017,27,27,Net Utility Operating Income (Carried forward ...,A,1994
64591,f1_incm_stmnt_2,2017,28,28,Other Income and Deductions,A,1994
64634,f1_incm_stmnt_2,2017,29,29,Other Income,A,1994
64678,f1_incm_stmnt_2,2017,30,30,Nonutilty Operating Income,A,1994
64721,f1_incm_stmnt_2,2017,31,31,"Revenues From Merchandising, Jobbing and Contr...",A,1994
64764,f1_incm_stmnt_2,2017,32,32,"(Less) Costs and Exp. of Merchandising, Job. &...",A,1994
64806,f1_incm_stmnt_2,2017,33,33,Revenues From Nonutility Operations (417),A,1994
64848,f1_incm_stmnt_2,2017,34,34,(Less) Expenses of Nonutility Operations (417.1),A,1994
64889,f1_incm_stmnt_2,2017,35,35,Nonoperating Rental Income (418),A,1994
64929,f1_incm_stmnt_2,2017,36,36,Equity in Earnings of Subsidiary Companies (41...,A,1994
64969,f1_incm_stmnt_2,2017,37,37,Interest and Dividend Income (419),A,1994
65008,f1_incm_stmnt_2,2017,38,38,Allowance for Other Funds Used During Construc...,A,1994
65047,f1_incm_stmnt_2,2017,39,39,Miscellaneous Nonoperating Income (421),A,1994
65085,f1_incm_stmnt_2,2017,40,40,Gain on Disposition of Property (421.1),A,1994
65123,f1_incm_stmnt_2,2017,41,41,TOTAL Other Income (Enter Total of lines 31 th...,A,1994
65157,f1_incm_stmnt_2,2017,42,42,Other Income Deductions,A,1994
65187,f1_incm_stmnt_2,2017,43,43,Loss on Disposition of Property (421.2),A,1994
65216,f1_incm_stmnt_2,2017,44,44,Miscellaneous Amortization (425),A,1994
65243,f1_incm_stmnt_2,2017,45,45,Donations (426.1),A,2004
65266,f1_incm_stmnt_2,2017,46,46,Life Insurance (426.2),A,2004
65288,f1_incm_stmnt_2,2017,47,47,Penalties (426.3),A,2004
65306,f1_incm_stmnt_2,2017,48,48,"Exp. for Certain Civic, Political & Related ...",A,2004
65319,f1_incm_stmnt_2,2017,49,49,Other Deductions (426.5),A,2004
65332,f1_incm_stmnt_2,2017,50,46,TOTAL Other Income Deductions (Total of lines ...,A,1994
65342,f1_incm_stmnt_2,2017,51,47,Taxes Applic. to Other Income and Deductions,A,1994
65352,f1_incm_stmnt_2,2017,52,48,Taxes Other Than Income Taxes (408.2),A,1994
65362,f1_incm_stmnt_2,2017,53,49,Income Taxes-Federal (409.2),A,1994
65372,f1_incm_stmnt_2,2017,54,50,Income Taxes-Other (409.2),A,1994
65381,f1_incm_stmnt_2,2017,55,51,Provision for Deferred Inc. Taxes (410.2),A,1994
65390,f1_incm_stmnt_2,2017,56,52,(Less) Provision for Deferred Income Taxes-Cr....,A,1994
65399,f1_incm_stmnt_2,2017,57,53,Investment Tax Credit Adj.-Net (411.5),A,1994
65408,f1_incm_stmnt_2,2017,58,54,(Less) Investment Tax Credits (420),A,1994
65417,f1_incm_stmnt_2,2017,59,55,TOTAL Taxes on Other Income and Deductions (To...,A,1994
65426,f1_incm_stmnt_2,2017,60,56,Net Other Income and Deductions (Total of line...,A,1994
65435,f1_incm_stmnt_2,2017,61,57,Interest Charges,A,1994
65444,f1_incm_stmnt_2,2017,62,58,Interest on Long-Term Debt (427),A,1994
65453,f1_incm_stmnt_2,2017,63,59,Amort. of Debt Disc. and Expense (428),A,1994
65462,f1_incm_stmnt_2,2017,64,60,Amortization of Loss on Reaquired Debt (428.1),A,1994
65471,f1_incm_stmnt_2,2017,65,61,(Less) Amort. of Premium on Debt-Credit (429),A,1994
65480,f1_incm_stmnt_2,2017,66,62,(Less) Amortization of Gain on Reaquired Debt-...,A,1994
65488,f1_incm_stmnt_2,2017,67,63,Interest on Debt to Assoc. Companies (430),A,1994
65496,f1_incm_stmnt_2,2017,68,64,Other Interest Expense (431),A,1994
65504,f1_incm_stmnt_2,2017,69,65,(Less) Allowance for Borrowed Funds Used Durin...,A,1994
65512,f1_incm_stmnt_2,2017,70,66,Net Interest Charges (Total of lines 62 thru 69),A,1994
65519,f1_incm_stmnt_2,2017,71,67,Income Before Extraordinary Items (Total of li...,A,1994
65526,f1_incm_stmnt_2,2017,72,68,Extraordinary Items,A,1994
65533,f1_incm_stmnt_2,2017,73,69,Extraordinary Income (434),A,1994
65540,f1_incm_stmnt_2,2017,74,70,(Less) Extraordinary Deductions (435),A,1994
65547,f1_incm_stmnt_2,2017,75,71,Net Extraordinary Items (Total of line 73 less...,A,1994
65554,f1_incm_stmnt_2,2017,76,72,Income Taxes-Federal and Other (409.3),A,1994
65561,f1_incm_stmnt_2,2017,77,73,Extraordinary Items After Taxes (line 75 less ...,A,1994
65567,f1_incm_stmnt_2,2017,78,74,Net Income (Total of line 71 and 77),A,1994

In [ ]:
(
    elec_income_row_literals
    .query("report_year==2018")
    .sort_values("row_number")
)