In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
# Standard libraries
import logging
import sys
import os
import pathlib

# 3rd party libraries
import geopandas as gpd
import dask.dataframe as dd
from dask.distributed import Client
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import pandas as pd
import seaborn as sns
import sqlalchemy as sa
#import pickle

# Local libraries
import pudl

In [4]:
# Enable viewing of logging outputs
logger=logging.getLogger()
logger.setLevel(logging.INFO)
handler = logging.StreamHandler(stream=sys.stdout)
formatter = logging.Formatter('%(message)s')
handler.setFormatter(formatter)
logger.handlers = [handler]

In [5]:
# Establish connection to pudl database
pudl_settings = pudl.workspace.setup.get_defaults()
pudl_engine = sa.create_engine(pudl_settings['pudl_db'])
pudl_out = pudl.output.pudltabl.PudlTabl(
    pudl_engine=pudl_engine,
    freq='AS'
)

In [6]:
eia = pudl_out.gens_eia860()
steam = pudl_out.plants_steam_ferc1()

In [14]:
steam[steam['plant_id_pudl']==41]
#steam[steam['plant_name_ferc1'].str.contains('ninemile')]

,report_year,utility_id_ferc1,utility_id_pudl,utility_name_ferc1,plant_id_pudl,plant_id_ferc1,plant_name_ferc1,asset_retirement_cost,avg_num_employees,capacity_factor,...,opex_steam,opex_steam_other,opex_structures,opex_transfer,peak_demand_mw,plant_capability_mw,plant_hours_connected_while_generating,plant_type,record_id,water_limited_capacity_mw
27538,2010,151,280,Rochester Gas and Electric Corporation,41,553,beebee station,3412569.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,steam,f1_steam_2010_12_151_0_5,NaN
27539,2011,151,280,Rochester Gas and Electric Corporation,41,553,beebee station,3412569.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,steam,f1_steam_2011_12_151_0_5,NaN
27540,2012,151,280,Rochester Gas and Electric Corporation,41,553,beebee station,3412569.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7791.0,steam,f1_steam_2012_12_151_0_5,NaN
27541,2013,151,280,Rochester Gas and Electric Corporation,41,553,beebee station,3412569.0,NaN,0.00069,...,NaN,NaN,NaN,NaN,19.0,NaN,201.0,steam,f1_steam_2013_12_151_0_5,NaN
27542,2014,151,280,Rochester Gas and Electric Corporation,41,553,beebee station,7568959.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,steam,f1_steam_2014_12_151_0_5,NaN
27543,2015,151,280,Rochester Gas and Electric Corporation,41,553,beebee station,2010116.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,steam,f1_steam_2015_12_151_0_5,NaN

In [ ]:
Entergy Louisiana, LLC
ninemile point 4 & 5